name: Hungary 140-7

on:
  schedule:
    - cron: '20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['00/55.9', '00/56.0', '00/56.0', '00/56.5', '59/57.5']
    steps:
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG }}
      - name: Test python
        run: |
          BASE_URL=${{ secrets.BASE_URL }}
          python3 v_h/h.py ${{ matrix.tag }} "140" "7" "$BASE_URL"
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: send custom message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            IP for ${{ matrix.tag }}
            IP6: ${{ steps.ip.outputs.ipv6 }}
            IP4: ${{ steps.ip.outputs.ipv4 }}